name: Backend AI Agent Tests v2

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  ai-agent-tests:
    name: Test AI Agents (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install basic dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install pydantic typing-extensions
        
    - name: Install project dependencies
      working-directory: backend
      continue-on-error: true
      run: |
        pip install -r requirements.txt || echo "Some optional dependencies failed"
        
    - name: Show environment info
      working-directory: backend
      run: |
        echo "=== Environment Debug Info ==="
        echo "Python: $(python --version)"
        echo "Pip: $(pip --version)"
        echo "Working Directory: $(pwd)"
        echo "Files in backend:"
        ls -la | head -10
        echo "Python files:"
        find . -name "*.py" -type f | head -10
        
    - name: Run AI Agent Tests
      working-directory: backend
      run: |
        echo "=== Starting AI Agent Tests ==="
        python test_agents_standalone.py
        echo "=== AI Agent Tests Completed ==="
        
    - name: Run Demo Tests
      working-directory: backend
      continue-on-error: true
      run: |
        echo "=== Starting Demo Tests ==="
        python simple_test_demo.py || echo "Demo completed with warnings"
        echo "=== Demo Tests Completed ==="
        
    - name: Test Summary
      if: always()
      run: |
        echo "## 🎯 AI Agent Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Python Version:** ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Type:** Standalone AI Agent Tests" >> $GITHUB_STEP_SUMMARY
        echo "- **Components Tested:**" >> $GITHUB_STEP_SUMMARY
        echo "  - Mock Infrastructure (LLM, Brave Search, Mem0)" >> $GITHUB_STEP_SUMMARY
        echo "  - Pydantic Models (Template, Story, Clue)" >> $GITHUB_STEP_SUMMARY
        echo "  - Agent Response Mocks" >> $GITHUB_STEP_SUMMARY
        echo "  - Error Handling Patterns" >> $GITHUB_STEP_SUMMARY

  security-check:
    name: Security Scan
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Run security scan
      working-directory: backend
      continue-on-error: true
      run: |
        echo "=== Security Scan ==="
        pip install bandit
        bandit -r . -f json || echo "Security scan completed"
        echo "=== Security Scan Completed ==="
